#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

def image_callback(msg):
    # Mengonversi pesan Image menjadi citra OpenCV
    bridge = CvBridge()
    cv_image = bridge.imgmsg_to_cv2(msg, "bgr8")

    # Menampilkan citra
    cv2.imshow("Camera", cv_image)
    cv2.waitKey(1)

def camera_subscriber():
    # Inisialisasi node ROS dengan nama "camera_subscriber"
    rospy.init_node('camera_subscriber', anonymous=True)

    # Membuat objek subscriber untuk menerima citra dari topik '/camera/image_raw'
    rospy.Subscriber('/camera/image_raw', Image, image_callback)

    # Loop terus menerus
    rospy.spin()

if __name__ == '__main__':
    try:
        # Memanggil fungsi camera_subscriber
        camera_subscriber()
    except rospy.ROSInterruptException:
        pass
